services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eb-api
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    container_name: eb-db
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 5
